/*
 * GLP-3.0 License.
 */
package omega.services;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Breno Viana
 * @author Murilo Bento
 */
public class ChatGUI extends javax.swing.JFrame {

    // 
    private final static String CHAT_SCREEN = "CHAT_SCREEN";
    private final static String MAIN_SCREEN = "MAIN_SCREEN";
    private final static String MAIN_CONFIG_PANEL = "MAIN_CONFIG_PANEL";
    private final static String CREATE_CHAT_ROOM = "CREATE_CHAT_ROOM";
    private final static String ENTER_CHAT_ROOM = "CHOOSE_CHAT_ROOM";
    private final static String CONFIGURE_USER = "CONFIGURE_USER";

    // Card layout
    private final CardLayout card;
    private final CardLayout chatCard;

    /**
     * Creates new form ChatGUI
     */
    public ChatGUI() {
        initComponents();
        // Center window
        setLocationRelativeTo(this);
        // Chat layout
        this.chatCard = new CardLayout();
        this.jBackground.setLayout(this.chatCard);
        this.jBackground.add(this.jMainPanel, MAIN_SCREEN);
        this.jBackground.add(this.jChatPanel, CHAT_SCREEN);
        // 
        this.card = new CardLayout();
        this.jConfigPanel.setLayout(this.card);
        this.jConfigPanel.add(this.jMainScreenPanel, MAIN_CONFIG_PANEL);
        this.jConfigPanel.add(this.jEnterChatRoomPanel, ENTER_CHAT_ROOM);
        this.jConfigPanel.add(this.jCreateChatRoomPanel, CREATE_CHAT_ROOM);
        this.jConfigPanel.add(this.jConfigureUserPanel, CONFIGURE_USER);
    }

    public void run() {
        try {
            for (UIManager.LookAndFeelInfo info
                    : UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException |
                IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ChatGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ChatGUI().setVisible(true);
        });
    }
    
    private void updateUserData() {
        // TODO
        // - Update user data
        // - Show confimation message
        // Change screen
        this.card.show(this.jConfigPanel, MAIN_CONFIG_PANEL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEnterChatRoomPanel = new javax.swing.JPanel();
        jEnterButton = new javax.swing.JButton();
        jCRNameEnterCR = new javax.swing.JTextField();
        jBackButtonEnterCR = new javax.swing.JButton();
        jEnterCRTitleLabel = new javax.swing.JLabel();
        jMainScreenPanel = new javax.swing.JPanel();
        jCreateChatRoomButton = new javax.swing.JButton();
        jEnterChatRoomButton = new javax.swing.JButton();
        jConfigureUserButton = new javax.swing.JButton();
        jCreateChatRoomPanel = new javax.swing.JPanel();
        jCreateButton = new javax.swing.JButton();
        jCRNameCreateCR = new javax.swing.JTextField();
        jBackButtonCreateCR = new javax.swing.JButton();
        jCreateCRTitleLabel = new javax.swing.JLabel();
        jMainPanel = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        jConfigPanel = new javax.swing.JPanel();
        jChatPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jConfigureUserPanel = new javax.swing.JPanel();
        jConfirmButton = new javax.swing.JButton();
        jUserNickname = new javax.swing.JTextField();
        jBackButtonEnterCR1 = new javax.swing.JButton();
        jEnterCRTitleLabel1 = new javax.swing.JLabel();
        jUserNickname1 = new javax.swing.JTextField();
        jEnterCRTitleLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jEnterCRTitleLabel3 = new javax.swing.JLabel();
        jBackground = new javax.swing.JPanel();

        jEnterChatRoomPanel.setBackground(new java.awt.Color(255, 255, 255));
        jEnterChatRoomPanel.setPreferredSize(new java.awt.Dimension(500, 275));

        jEnterButton.setText("Enter");
        jEnterButton.setFocusPainted(false);
        jEnterButton.setRequestFocusEnabled(false);
        jEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnterButtonActionPerformed(evt);
            }
        });

        jCRNameEnterCR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCRNameEnterCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRNameEnterCRActionPerformed(evt);
            }
        });

        jBackButtonEnterCR.setText("Back");
        jBackButtonEnterCR.setFocusPainted(false);
        jBackButtonEnterCR.setRequestFocusEnabled(false);
        jBackButtonEnterCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonEnterCRActionPerformed(evt);
            }
        });

        jEnterCRTitleLabel.setText("Chat Room Name:");

        javax.swing.GroupLayout jEnterChatRoomPanelLayout = new javax.swing.GroupLayout(jEnterChatRoomPanel);
        jEnterChatRoomPanel.setLayout(jEnterChatRoomPanelLayout);
        jEnterChatRoomPanelLayout.setHorizontalGroup(
            jEnterChatRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEnterChatRoomPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jEnterChatRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jEnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCRNameEnterCR, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBackButtonEnterCR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnterCRTitleLabel))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jEnterChatRoomPanelLayout.setVerticalGroup(
            jEnterChatRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEnterChatRoomPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jEnterCRTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCRNameEnterCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEnterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBackButtonEnterCR)
                .addGap(62, 62, 62))
        );

        jMainScreenPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainScreenPanel.setPreferredSize(new java.awt.Dimension(500, 275));

        jCreateChatRoomButton.setText("Create a Chat Room");
        jCreateChatRoomButton.setFocusPainted(false);
        jCreateChatRoomButton.setRequestFocusEnabled(false);
        jCreateChatRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateChatRoomButtonActionPerformed(evt);
            }
        });

        jEnterChatRoomButton.setText("Enter a Chat Room");
        jEnterChatRoomButton.setFocusPainted(false);
        jEnterChatRoomButton.setRequestFocusEnabled(false);
        jEnterChatRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnterChatRoomButtonActionPerformed(evt);
            }
        });

        jConfigureUserButton.setText("Configure User");
        jConfigureUserButton.setFocusPainted(false);
        jConfigureUserButton.setRequestFocusEnabled(false);
        jConfigureUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfigureUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMainScreenPanelLayout = new javax.swing.GroupLayout(jMainScreenPanel);
        jMainScreenPanel.setLayout(jMainScreenPanelLayout);
        jMainScreenPanelLayout.setHorizontalGroup(
            jMainScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainScreenPanelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jMainScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCreateChatRoomButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEnterChatRoomButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jConfigureUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jMainScreenPanelLayout.setVerticalGroup(
            jMainScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainScreenPanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jCreateChatRoomButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jEnterChatRoomButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jConfigureUserButton)
                .addGap(79, 79, 79))
        );

        jCreateChatRoomPanel.setBackground(new java.awt.Color(255, 255, 255));
        jCreateChatRoomPanel.setPreferredSize(new java.awt.Dimension(500, 275));

        jCreateButton.setText("Create");
        jCreateButton.setFocusPainted(false);
        jCreateButton.setRequestFocusEnabled(false);
        jCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateButtonActionPerformed(evt);
            }
        });

        jCRNameCreateCR.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCRNameCreateCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCRNameCreateCRActionPerformed(evt);
            }
        });

        jBackButtonCreateCR.setText("Back");
        jBackButtonCreateCR.setFocusPainted(false);
        jBackButtonCreateCR.setRequestFocusEnabled(false);
        jBackButtonCreateCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonCreateCRActionPerformed(evt);
            }
        });

        jCreateCRTitleLabel.setText("Chat Room Name:");

        javax.swing.GroupLayout jCreateChatRoomPanelLayout = new javax.swing.GroupLayout(jCreateChatRoomPanel);
        jCreateChatRoomPanel.setLayout(jCreateChatRoomPanelLayout);
        jCreateChatRoomPanelLayout.setHorizontalGroup(
            jCreateChatRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCreateChatRoomPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jCreateChatRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCRNameCreateCR, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBackButtonCreateCR, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCreateCRTitleLabel))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jCreateChatRoomPanelLayout.setVerticalGroup(
            jCreateChatRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCreateChatRoomPanelLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jCreateCRTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCRNameCreateCR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCreateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBackButtonCreateCR)
                .addGap(62, 62, 62))
        );

        jMainPanel.setBackground(new java.awt.Color(255, 255, 255));
        jMainPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omega/assets/omega.png"))); // NOI18N

        jConfigPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jConfigPanelLayout = new javax.swing.GroupLayout(jConfigPanel);
        jConfigPanel.setLayout(jConfigPanelLayout);
        jConfigPanelLayout.setHorizontalGroup(
            jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jConfigPanelLayout.setVerticalGroup(
            jConfigPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jConfigPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jConfigPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jChatPanel.setBackground(new java.awt.Color(255, 255, 255));
        jChatPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setText("Leave Room");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jChatPanelLayout = new javax.swing.GroupLayout(jChatPanel);
        jChatPanel.setLayout(jChatPanelLayout);
        jChatPanelLayout.setHorizontalGroup(
            jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(jChatPanelLayout.createSequentialGroup()
                .addComponent(jTextField1)
                .addGap(0, 0, 0)
                .addComponent(jButton1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jChatPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jChatPanelLayout.setVerticalGroup(
            jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jChatPanelLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jConfigureUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        jConfigureUserPanel.setPreferredSize(new java.awt.Dimension(500, 275));

        jConfirmButton.setText("Confirm");
        jConfirmButton.setFocusPainted(false);
        jConfirmButton.setRequestFocusEnabled(false);
        jConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmButtonActionPerformed(evt);
            }
        });

        jUserNickname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUserNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNicknameActionPerformed(evt);
            }
        });

        jBackButtonEnterCR1.setText("Back");
        jBackButtonEnterCR1.setFocusPainted(false);
        jBackButtonEnterCR1.setRequestFocusEnabled(false);
        jBackButtonEnterCR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonEnterCR1ActionPerformed(evt);
            }
        });

        jEnterCRTitleLabel1.setText("Nickname:");

        jUserNickname1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUserNickname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUserNickname1ActionPerformed(evt);
            }
        });

        jEnterCRTitleLabel2.setText("Username:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jEnterCRTitleLabel3.setText("Language:");

        javax.swing.GroupLayout jConfigureUserPanelLayout = new javax.swing.GroupLayout(jConfigureUserPanel);
        jConfigureUserPanel.setLayout(jConfigureUserPanelLayout);
        jConfigureUserPanelLayout.setHorizontalGroup(
            jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfigureUserPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jEnterCRTitleLabel1)
                    .addComponent(jEnterCRTitleLabel2)
                    .addComponent(jEnterCRTitleLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBackButtonEnterCR1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jConfirmButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUserNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jConfigureUserPanelLayout.setVerticalGroup(
            jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfigureUserPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnterCRTitleLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUserNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnterCRTitleLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jConfigureUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEnterCRTitleLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jConfirmButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBackButtonEnterCR1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jBackground.setBackground(new java.awt.Color(255, 255, 255));
        jBackground.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jBackgroundLayout = new javax.swing.GroupLayout(jBackground);
        jBackground.setLayout(jBackgroundLayout);
        jBackgroundLayout.setHorizontalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jBackgroundLayout.setVerticalGroup(
            jBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCreateChatRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateChatRoomButtonActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, CREATE_CHAT_ROOM);
    }//GEN-LAST:event_jCreateChatRoomButtonActionPerformed

    private void jEnterChatRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnterChatRoomButtonActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, ENTER_CHAT_ROOM);
    }//GEN-LAST:event_jEnterChatRoomButtonActionPerformed

    private void jBackButtonCreateCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonCreateCRActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, MAIN_CONFIG_PANEL);
    }//GEN-LAST:event_jBackButtonCreateCRActionPerformed

    private void jBackButtonEnterCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonEnterCRActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, MAIN_CONFIG_PANEL);
    }//GEN-LAST:event_jBackButtonEnterCRActionPerformed

    private void jCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateButtonActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, MAIN_CONFIG_PANEL);
        this.chatCard.show(this.jBackground, CHAT_SCREEN);
    }//GEN-LAST:event_jCreateButtonActionPerformed

    private void jEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEnterButtonActionPerformed

    private void jConfigureUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfigureUserButtonActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, CONFIGURE_USER);
    }//GEN-LAST:event_jConfigureUserButtonActionPerformed

    private void jConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmButtonActionPerformed
        updateUserData();
    }//GEN-LAST:event_jConfirmButtonActionPerformed

    private void jBackButtonEnterCR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonEnterCR1ActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, MAIN_CONFIG_PANEL);
    }//GEN-LAST:event_jBackButtonEnterCR1ActionPerformed

    private void jCRNameCreateCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRNameCreateCRActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, CREATE_CHAT_ROOM);
    }//GEN-LAST:event_jCRNameCreateCRActionPerformed

    private void jCRNameEnterCRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCRNameEnterCRActionPerformed
        // Change screen
        this.card.show(this.jConfigPanel, ENTER_CHAT_ROOM);
    }//GEN-LAST:event_jCRNameEnterCRActionPerformed

    private void jUserNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNicknameActionPerformed
        updateUserData();
    }//GEN-LAST:event_jUserNicknameActionPerformed

    private void jUserNickname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNickname1ActionPerformed
        updateUserData();
    }//GEN-LAST:event_jUserNickname1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Change screen
        this.chatCard.show(this.jBackground, MAIN_SCREEN);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButtonCreateCR;
    private javax.swing.JButton jBackButtonEnterCR;
    private javax.swing.JButton jBackButtonEnterCR1;
    private javax.swing.JPanel jBackground;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCRNameCreateCR;
    private javax.swing.JTextField jCRNameEnterCR;
    private javax.swing.JPanel jChatPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jConfigPanel;
    private javax.swing.JButton jConfigureUserButton;
    private javax.swing.JPanel jConfigureUserPanel;
    private javax.swing.JButton jConfirmButton;
    private javax.swing.JButton jCreateButton;
    private javax.swing.JLabel jCreateCRTitleLabel;
    private javax.swing.JButton jCreateChatRoomButton;
    private javax.swing.JPanel jCreateChatRoomPanel;
    private javax.swing.JButton jEnterButton;
    private javax.swing.JLabel jEnterCRTitleLabel;
    private javax.swing.JLabel jEnterCRTitleLabel1;
    private javax.swing.JLabel jEnterCRTitleLabel2;
    private javax.swing.JLabel jEnterCRTitleLabel3;
    private javax.swing.JButton jEnterChatRoomButton;
    private javax.swing.JPanel jEnterChatRoomPanel;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jMainScreenPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jUserNickname;
    private javax.swing.JTextField jUserNickname1;
    // End of variables declaration//GEN-END:variables
}
